# This tells Netlify to use the Flutter build plugin.
[[plugins]]
package = "netlify-plugin-flutter"

# This tells the plugin to use the latest STABLE version of Flutter.
[plugins.inputs]
channel = "stable"